name: dockerpush

on:
  push:
    branches: [main]
concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [linux/amd64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push arch image (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.arch }}
          push: true
          tags: nl2109/modsentinel:latest-${{ matrix.arch##*/ }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
          provenance: false

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push manifest
        uses: docker/buildx-action@v0
        with:
          endpoint: default
      - name: Push manifest list
        run: |
          docker buildx imagetools create -t nl2109/modsentinel:latest \
            nl2109/modsentinel:latest-amd64
